### ISSUE TITLE
Native: Parsing Error

### ISSUE THREAD

**Issue by gesker** [quarkiverse/quarkus-primefaces#30]
When trying to compile using native profile I'm getting a parser error.  Adding the  jakarta-el dependency resolves the issue:

```
        <dependency>
            <groupId>jakarta.el</groupId>
            <artifactId>jakarta.el-api</artifactId>
            <version>5.0.0</version>
        </dependency>
```

That seems to be the most current version over at [maven](https://mvnrepository.com/artifact/jakarta.el/jakarta.el-api) but not sure if there is a newer version related to Jakarta EE 10. This "might" be a leftover from version 9.

**Anyway, could this dependency be added directly to quarkus-primefaces?**

Parsing error thrown **without** this jar is:

```
Fatal error: com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing org.primefaces.el.InterceptingResolver.getFeatureDescriptors(jakarta.el.ELContext, java.lang.Object) 
Parsing context:
   at org.primefaces.el.InterceptingResolver.getFeatureDescriptors(InterceptingResolver.java:77)
   at org.primefaces.el.InterceptingResolver.getFeatureDescriptors(InterceptingResolver.java:77)
[snip]
   at org.primefaces.el.InterceptingResolver.getFeatureDescriptors(InterceptingResolver.java:77)
   at org.primefaces.el.InterceptingResolver.getFeatureDescriptors(InterceptingResolver.java:77)

        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:153)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.createFlowsGraph(MethodTypeFlow.java:104)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureFlowsGraphCreated(MethodTypeFlow.java:83)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.getOrCreateMethodFlowsGraph(MethodTypeFlow.java:65)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.typestate.DefaultSpecialInvokeTypeFlow.onObservedUpdate(DefaultSpecialInvokeTypeFlow.java:61)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.TypeFlow.lambda$addObserver$0(TypeFlow.java:455)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:193)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:177)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: jakarta.el.ELResolver.getFeatureDescriptors(jakarta.el.ELContext, java.lang.Object). This error is reported at image build time because class org.primefaces.el.InterceptingResolver is registered for linking at image build time by command line
        at parsing org.primefaces.el.InterceptingResolver.getFeatureDescriptors(InterceptingResolver.java:77)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2518)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.throwParserError(SharedGraphBuilderPhase.java:110)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3393)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.handleBytecodeBlock(BytecodeParser.java:3345)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3190)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1138)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:1030)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:97)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase.run(SharedGraphBuilderPhase.java:84)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.run(Phase.java:49)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:446)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.AnalysisParsedGraph.parseBytecode(AnalysisParsedGraph.java:135)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisMethod.ensureGraphParsed(AnalysisMethod.java:685)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:171)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:349)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.createFlowsGraph(MethodTypeFlow.java:93)
        ... 12 more
Caused by: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: jakarta.el.ELResolver.getFeatureDescriptors(jakarta.el.ELContext, java.lang.Object). This error is reported at image build time because class org.primefaces.el.InterceptingResolver is registered for linking at image build time by command line
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.reportUnresolvedElement(SharedGraphBuilderPhase.java:333)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.handleUnresolvedMethod(SharedGraphBuilderPhase.java:323)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.handleUnresolvedInvoke(SharedGraphBuilderPhase.java:279)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeVirtual(BytecodeParser.java:1721)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5286)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3385)
        ... 27 more

```

**Comment by melloware** [comment]
Interesting because the MyFaces Quarkus Extension already has this...and it was working for the previous rev?

```xml
        <!-- EL implementation -->
        <dependency>
            <groupId>org.apache.tomcat</groupId>
            <artifactId>tomcat-jasper-el</artifactId>
            <version>11.0.0-M1</version>
        </dependency>
```

**Comment by melloware** [comment]
See this:
![image](https://user-images.githubusercontent.com/4399574/228945957-d573bc9a-0b4a-47cc-b3ec-c732dc6e6a10.png)

**Comment by melloware** [comment]
My GitHub Actions does a native build of a PrimeFaces app every time I commit and you can see the Native build worked here: https://github.com/quarkiverse/quarkus-primefaces/actions/runs/4568837815/jobs/8064383108

**Comment by melloware** [comment]
When I run `mvn dependency:tree | grep el-api` on my Quarkus Faces project I get this...

```
[INFO] |  |  \- jakarta.el:jakarta.el-api:jar:5.0.1:compile
[INFO] |  |  \- org.apache.tomcat:tomcat-el-api:jar:11.0.0-M3:compile
```

**Comment by gesker** [comment]
My guess is that the Quarkus Faces project would not build if it was not importing quarkus-hibernate-validator which contains the transitive jakarta.el-api and would throw "unresolved method during parsing: jakarta.el.ELResolver" ??

**Comment by gesker** [comment]
Mostly kicking out reports and charts from sql views almost no user input
on this service. Sort of a micro-ui.
On anything bigger I probably wouldn't have noticed. EL was a head
scratcher there for a minute.

**Comment by melloware** [comment]
OK added to the pom.xml no harm in me adding it here.

**Comment by gesker** [comment]
If this is really a once in a blue moon kind of a thing a DNF or Won't Fix is not the end of the world AT ALL.
Like you pointed out it is probably very unlikely that most won't have validators in place.
In any event... Thank you, Sir @melloware!

**Comment by melloware** [comment]
Interesting check this out I am getting a native build failure now on GitHub Actions: https://github.com/quarkiverse/quarkus-primefaces/actions/runs/4577321096/jobs/8082584255

**Comment by gesker** [comment]
Can you pull that dependency back out?

**Comment by melloware** [comment]
Yep I reversed it I just can't explain why that break it when you said it solves your issue.

**Comment by gesker** [comment]
I simplified my current project/module (micro ui that doesn't include validators) and the module again compiles down to native -- no parser errors. So, a step forward.

But, as soon as I get a successful native package I'm again getting "Warning: Could not resolve java.xxx for reflection Reason"  Now, I kind of expected to require adding some @RegisterForReflection decorations to my own classes but I didn't think these for " java" and jakarta .faces classes wold be something I'd see so scratching my head on that. So, a step backward.

![image](https://user-images.githubusercontent.com/6843294/229295144-7863a6e7-338e-44df-9ff7-e40644a26502.png)

Actually, to the point of thinking my dev station was setup oddly wrong for some reason so I fired up a vanilla vm, setup a fresh debian/openjdk environment and seeing the strange warnings there, too.

So, just tried a couple of other projects where the aim is to flip some traditional wars to quarkus where primefaces is one of the maven submodules and kind of the same thing. First round after bumping to 3.0.0 CR1. All is fine in regular packaging. Things run quite well. As soon as try to package native I'm chasing jar/lib conflicts that kind of don't make sense at first look like - especially after this discussion her on  this issue, and https://github.com/quarkiverse/quarkus-primefaces/issues/32 and https://github.com/quarkiverse/quarkus-primefaces/issues/31.

All good -- and actually quite snappy btw -- until I try to package native.

I was going to joke that I got caught in jar hell Friday but now I'm not sure which hell I'm in? :)

I've got a lot of these projects and over time I got very disciplined about my "dependencyManagement" configuration it it's relationship to the sub-modules. I haven't visited jar hell in a long long loooong time.

My guess is probably not jar hell but more of a "I just hit a steeper part of my grallvm learning curve." For instance, not related to this but similar experience, I ran into a self inflicted wound on a misplaced decoration that was in the wrong place for a sub-module where the service was interacting with the db. Never got an error in Quarkus 2.x. Then in getting ready for the upgrade to Quarkus 3 I got errors and I blew a few days trying to understand what graalvm was telling me until a kind soul over at Quarkus threw me a little help here https://github.com/quarkusio/quarkus/issues/32188#issuecomment-1489776829 and here https://github.com/quarkusio/quarkus/issues/32298.

In the new week, probably later in the week, I think I'm going to carve out some time to try create a new mulit-module project with a single ui module and connect it to a single service module and try to zero in. If I can get a reliable failure I'll create a reproducer.

Thank you so much @melloware for your patience and have a great weekend!

**Comment by melloware** [comment]
Yep let me know.  I am more than happy to tweak GraalVm settings in PF, OmniFaces, MyFaces if we find stuff missing but minimal reproducers definitely help!   I have always been using QuarkusFaces since its a worst case scenario "uses everything".
