### ISSUE TITLE
Native: ImageCropper NullPointerException

### ISSUE THREAD

**Issue by melloware** [quarkiverse/quarkus-primefaces#8]
Running in Native mode and cropping image results in:

```
 java.lang.NullPointerException
 at org.primefaces.component.imagecropper.ImageCropperRenderer.getConvertedValue(ImageCropperRenderer.java:226)
        at javax.faces.component.UIInput.getConvertedValue(UIInput.java:772)
```

I think the error is because webRoot or imageRoot is NULL

```java
String webRoot = externalContext.getRealPath(Constants.EMPTY_STRING);
String fileSeparator = Constants.EMPTY_STRING;
if (!(webRoot.endsWith("\\") || webRoot.endsWith("/")) &&
         !(imagePath.startsWith("\\") || imagePath.startsWith("/"))) {
     fileSeparator = "/";
}
```

**Comment by melloware** [comment]
PF 13 is out
